services:
  db:
    image: postgres:15
    container_name: url-shortener-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: url_shortener
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/sql/:/docker-entrypoint-initdb.d/


  server:
    build: ./server
    container_name: url-shortener-server
    restart: always
    depends_on:
      - db
    environment:
      PORT: 5001
      DATABASE_URL: postgres://postgres:admin1234@db:5432/url_shortener
      JWT_SECRET: my_jwt_secret_key
      BASE_URL: http://localhost:5001
    ports:
      - "5001:5001"
    
  client:
    build: 
      context: ./client
      args:
        VITE_BASE_URL: http://localhost:5001
    container_name: url-shortener-client
    restart: always
    depends_on:
      - server
    ports:
      - "5173:80"
  
volumes:
  postgres_data: